import { COLORS } from "../assets/colors.js";
import { Dimensions, StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.white,
  },
  view: {
    height: "100%",
    alignItems: "center",
    justifyContent: "center",
    padding: 30,
  },
  fullWidth: {
    width: "100%",
  },
  centerView: {
    width: "100%",
    alignItems: "center",
  },
  logo: {
    marginBottom: 60,
  },
  span: {
    color: COLORS.black,
    fontWeight: "600",
    fontSize: 16,
    alignSelf: "flex-end",
    marginBottom: 30,
    marginTop: 10,
    fontFamily: "Nunito-Bold",
  },
  divider: {
    width: "100%",
  },
  createAccount: {
    fontSize: 16,
    color: COLORS.black,
    marginTop: 14,
    fontFamily: "Nunito",
  },
  bottomInfo: {
    position: "absolute",
    width: "100%",
    alignItems: "center",
    bottom: 40,
  },
  input: (top) => ({
    width: "100%",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: COLORS.lightGray,
    borderRadius: 7,
    height: 48,
    paddingVertical: 12,
    paddingHorizontal: 18,
    textAlign: "left",
    fontSize: 16,
    fontFamily: "Nunito-SemiBold",
    justifyContent: "center",
    marginTop: top,
  }),
  inputPassword: {
    justifyContent: "center",
  },
  eyeIcon: {
    alignSelf: "flex-end",
    position: "absolute",
    paddingRight: 18,
    paddingTop: 25,
  },
  buttonText: {
    color: COLORS.white,
    textAlign: "center",
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 2,
    fontFamily: "Nunito-Black",
  },
  button: {
    backgroundColor: COLORS.black,
    width: "100%",
    borderRadius: 7,
    height: 48,
    paddingVertical: 15,
  },
  errorInput: {
    width: "100%",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: COLORS.red,
    borderRadius: 7,
    height: 48,
    paddingVertical: 12,
    paddingHorizontal: 18,
    textAlign: "left",
    fontSize: 16,
    marginTop: 25,
    fontFamily: "Nunito-SemiBold",
    justifyContent: "center",
  },
  errorText: {
    position: "absolute",
    bottom: -16,
    color: COLORS.red,
    fontFamily: "Nunito-SemiBold",
    fontSize: 12,
  },
  signUpImage: {
    alignSelf: "flex-end",
    marginRight: -30,
    marginTop: 30,
  },
  title: (width, letterSpacing) => ({
    fontSize: 30,
    fontFamily: "Nunito-Medium",
    letterSpacing: letterSpacing,
    width: width,
    textAlign: "center",
    color: COLORS.black,
  }),
  titleBold: {
    fontFamily: "Nunito-ExtraBold",
    color: COLORS.black,
    fontSize: 28,
  },
  info: {
    textAlign: "center",
    fontSize: 18,
    fontFamily: "Nunito",
    minWidth: 230,
    width: "80%",
    marginTop: 55,
  },
  textLabelButton: (color) => ({
    color: color,
    fontSize: 22,
    letterSpacing: 2.5,
    fontFamily: "Nunito-Black",
  }),
  iconButton: {
    color: COLORS.purple,
  },
  arrowBack: {
    position: "absolute",
    alignSelf: "flex-start",
    left: 30,
    top: 90,
    paddingVertical: 10,
    paddingRight: 10,
  },
  step: (color, qtd) => ({
    backgroundColor: color,
    width: (Dimensions.get("window").width - (60 + (qtd - 1) * 5)) / qtd,
    height: 5,
    borderRadius: 7,
  }),
  stepsPosition: {
    position: "absolute",
    top: 70,
    alignSelf: "flex-start",
    left: 30,
  },
  steps: {
    display: "flex",
    width: "100%",
    alignItems: "flex-start",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  stepsCount: {
    position: "absolute",
    top: 100,
    alignSelf: "flex-end",
    right: 30,
  },
  stepsCountText: {
    fontFamily: "Nunito-ExtraBold",
    fontSize: 20,
    color: COLORS.lightGray,
  },
  displayRow: {
    display: "flex",
    flexDirection: "row",
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
  },
  gender: (gender) => ({
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    marginRight: gender === "MASCULINO" ? 25 : 0,
    marginLeft: gender === "FEMININO" ? 25 : 0,
    marginTop: 50,
  }),
  genderText: {
    fontFamily: "Nunito-ExtraBold",
    fontSize: 14,
    letterSpacing: 2.5,
    marginTop: 15,
    textAlign: "center",
    color: COLORS.black,
  },
  defaultText: (
    fontSize,
    align,
    fontFamily,
    width,
    letterSpacing,
    marginTop,
  ) => ({
    fontSize: fontSize,
    textAlign: align,
    fontFamily: fontFamily,
    width: width,
    letterSpacing: letterSpacing,
    marginTop: marginTop,
    color: COLORS.black,
  }),
  genderTextSelected: {
    fontFamily: "Nunito-ExtraBold",
    fontSize: 14,
    letterSpacing: 2.5,
    marginTop: 15,
    textAlign: "center",
    color: COLORS.white,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: COLORS.green,
    borderRadius: 7,
    paddingHorizontal: 15,
    paddingVertical: 8,
    backgroundColor: COLORS.green,
    overflow: "hidden",
  },
  defaultAnswerGender: {
    fontSize: 14,
    textAlign: "center",
    fontFamily: "Nunito-ExtraBold",
    width: "auto",
    letterSpacing: 2.5,
    marginTop: 50,
    color: COLORS.white,
    backgroundColor: COLORS.green,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: COLORS.green,
    borderRadius: 7,
    paddingHorizontal: 15,
    paddingVertical: 8,
    overflow: "hidden",
  },
  blankTextBox: (color) => ({
    fontSize: 36,
    color: color,
    fontFamily: "Nunito",
    textAlign: "center",
    marginTop: 40,
  }),
  blankTextBoxComp: {
    display: "flex",
    width: "100%",
    flexDirection: "row",
    alignItems: "baseline",
    justifyContent: "center",
  },
  complementaryText: {
    fontFamily: "Nunito",
    fontSize: 25,
  },
  labelSkipButton: {
    position: "absolute",
    bottom: 60,
    height: 70,
    alignItems: "center",
    justifyContent: "space-between",
  },
  labelButton: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
  },
  skipButton: {
    fontFamily: "Nunito-Black",
    fontSize: 16,
    letterSpacing: 2,
    color: COLORS.lighterGray,
  },
  errorTextBlank: (bottom) => ({
    backgroundColor: COLORS.lightRed,
    color: COLORS.red,
    fontFamily: "Nunito-SemiBold",
    fontSize: 16,
    textAlign: "center",
    paddingHorizontal: 32,
    paddingVertical: 14,
    borderRadius: 7,
    overflow: "hidden",
    position: "absolute",
    bottom: bottom,
  }),
  selectionLabel: (color, selected) => ({
    borderColor: color,
    borderWidth: 1,
    width: "100%",
    padding: 20,
    borderRadius: 7,
    marginTop: 20,
    backgroundColor: selected ? color : COLORS.white,
  }),
  textSelectionLabel: (color, selected) => ({
    color: selected ? COLORS.white : color,
    fontSize: 14,
    textTransform: "uppercase",
    fontFamily: "Nunito-ExtraBold",
    letterSpacing: 2,
    whiteSpace: "nowrap",
  }),
  expectations: {
    display: "flex",
    width: "100%",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  expect: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-end",
    width: (Dimensions.get("window").width - 80) / 2,
  },
  lines: {
    position: "absolute",
    bottom: -10,
  },
  userPhotoIcon: {
    width: 60,
    height: 60,
    borderRadius: 10,
  },
  photoStar: {
    position: "absolute",
    alignItems: "center",
    justifyContent: "center",
    bottom: -11,
    right: -12,
  },
  starText: {
    color: COLORS.white,
    fontFamily: "Nunito-ExtraBold",
    textAlign: "center",
    fontSize: 12,
    position: "absolute",
    top: 8,
    left: 7.5,
    width: 13,
  },
  titleHome: {
    fontSize: 20,
    fontFamily: "Nunito-ExtraBold",
    color: COLORS.black,
    textTransform: "uppercase",
  },
  nameColor: (textColor) => ({
    color: textColor,
  }),
  notificationIndicator: {
    backgroundColor: COLORS.pink,
    width: 10,
    height: 10,
    borderRadius: "100%",
    position: "absolute",
    right: 3,
    top: 4,
  },
  levelProgress: {
    display: "flex",
    flexDirection: "column",
    width: "100%",
    alignItems: "center",
  },
  barLevel: {
    backgroundColor: COLORS.lighterGray,
    width: "100%",
    height: 10,
    borderRadius: 7,
  },
  barLevelProgress: (progress, color) => ({
    width: progress,
    backgroundColor: color,
    position: "absolute",
    height: 10,
    borderRadius: 7,
  }),
  levelDetails: {
    display: "flex",
    width: "100%",
    justifyContent: "space-between",
    flexDirection: "row",
    alignItems: "center",
    marginTop: 10,
  },
  infoColor: (textColor) => ({
    color: textColor,
    fontSize: 16,
    fontFamily: "Nunito-ExtraBold",
  }),
  level: {
    color: COLORS.lightGray,
    fontFamily: "Nunito-Bold",
    fontSize: 16,
  },
  homeNotification: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 30,
  },
  homePhotoName: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
  },
  userNameGreeting: {
    marginLeft: 20,
  },
  homeHeader: {
    marginBottom: 20,
    display: "flex",
    flexDirection: "row",
  },
  dividerThin: {
    width: Dimensions.get("window").width,
    height: 0.3,
    marginTop: 20,
    backgroundColor: COLORS.lighterGray,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    marginLeft: -30,
  },
  navigationArea: {
    position: "absolute",
    display: "flex",
    flexDirection: "row",
    bottom: 0,
  },
  navigationBar: {
    width: Dimensions.get("window").width,
    display: "flex",
    flexDirection: "row",
    height: 85,
    justifyContent: "space-between",
    paddingHorizontal: 45,
    alignItems: "center",
    paddingVertical: 10,
    paddingTop: 0,
  },
  boxShadow: {
    backgroundColor: COLORS.white,
    width: "100%",
    height: 120,
    shadowColor: "#000000",
    shadowOpacity: 0.03,
    shadowRadius: 10,
    shadowOffset: {
      height: -2,
      width: 2,
    },
    position: "absolute",
  },
  navigationSelected: (color) => ({
    display: "flex",
    flexDirection: "row",
    backgroundColor: color,
    width: 4,
    height: 4,
    borderRadius: "100%",
    alignSelf: "center",
    position: "absolute",
    bottom: -10,
  }),
  exercisesImage: {
    width: 240,
    resizeMode: "stretch",
    height: 200,
    position: "absolute",
    right: -30,
    bottom: -25,
  },
  myExercises: {
    display: "flex",
    width: "100%",
    flexDirection: "column",
    alignItems: "center",
    height: 215,
  },
  headerMyExercises: {
    display: "flex",
    width: "100%",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  subtitleHome: {
    fontFamily: "Nunito-ExtraBold",
    fontSize: 18,
    letterSpacing: 1.5,
  },
  descriptionMyExercises: {
    display: "flex",
    flexDirection: "column",
    width: "100%",
    alignItems: "flex-start",
    height: "100%",
    justifyContent: "flex-end",
  },
  startMyExercises: {
    display: "flex",
    flexDirection: "row",
  },
  cardMyExercises: {
    marginTop: 20,
    borderColor: COLORS.green,
    borderWidth: 1,
    width: "100%",
    height: 150,
    borderRadius: 7,
    padding: 15,
  },
  descriptionExerciseTitle: (textColor) => ({
    fontFamily: "Nunito-ExtraBold",
    fontSize: 16,
    color: textColor,
    letterSpacing: 1.5,
    textAlign: "left",
  }),
  arrowSize: {
    width: 20,
    height: 20,
    resizeMode: "stretch",
  },
  levelDescription: {
    fontFamily: "Nunito-ExtraBold",
    fontSize: 18,
    color: COLORS.black,
    marginBottom: 5,
    textTransform: "uppercase",
  },
  home: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
    height: "100%",
    justifyContent: "flex-start",
    padding: 30,
    marginTop: 40,
  },
  exerciseCard: (cardColor) => ({
    borderColor: cardColor,
    borderWidth: 1,
    borderRadius: 7,
    width: (Dimensions.get("window").width - 80) / 2,
    height: 110,
    padding: 15,
    marginTop: 20,
  }),
  exerciseCardTitle: (textColor) => ({
    color: textColor,
    fontSize: 14,
    fontFamily: "Nunito-ExtraBold",
    textTransform: "uppercase",
  }),
  exerciseCardDesc: {
    fontSize: 12,
    fontFamily: "Nunito-Bold",
    color: COLORS.lightGray,
    textTransform: "uppercase",
  },
  exerciseCardImage: {
    position: "absolute",
    bottom: 10,
    right: 10,
  },
  favorites: {
    display: "flex",
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  rankingContainer: {
    width: "100%",
    height: "100%",
    marginTop: 60,
  },
  topRankPhoto: {
    width: 70,
    height: 70,
    borderRadius: 10,
  },
  starTopRank: {
    position: "absolute",
    top: -9,
    right: -9,
  },
  rank: {
    position: "absolute",
    bottom: -15,
    alignSelf: "center",
  },
  rankTextBackground: (backColor) => ({
    backgroundColor: backColor,
    width: 30,
    height: 30,
    borderRadius: "100%",
    paddingTop: 6,
  }),
  rankText: (textColor) => ({
    color: textColor,
    fontFamily: "Nunito-ExtraBold",
    fontSize: 16,
    textAlign: "center",
  }),
  rankTopInfo: (horizontal) => ({
    position: "absolute",
    alignSelf: "center",
    bottom: horizontal ? 10 : -70,
    right: horizontal ? -115 : "auto",
    width: 90,
  }),
  nameRankTop: {
    fontFamily: "Nunito-ExtraBold",
    color: COLORS.black,
    letterSpacing: 1,
    fontSize: 16,
    textAlign: "center",
  },
  pointsRankTop: (textColor) => ({
    fontFamily: "Nunito-ExtraBold",
    color: textColor,
    fontSize: 14,
    textTransform: "uppercase",
    textAlign: "center",
    letterSpacing: 1,
    display: "flex",
    flexWrap: "nowrap",
  }),
  descRankTop: {
    fontFamily: "Nunito-ExtraBold",
    color: COLORS.lightGray,
    textTransform: "capitalize",
    fontSize: 14,
    letterSpacing: 1,
    textAlign: "center",
  },
  ranking: {
    display: "flex",
    flexDirection: "row",
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    position: "absolute",
    top: 50,
  },
  rankingTop: {
    marginLeft: 40,
    marginRight: 40,
  },
  rankingLow: {
    marginBottom: -80,
  },
  rankingList: {
    display: "flex",
    flexDirection: "column",
    width: "100%",
  },
  rankingCard: (color) => ({
    borderColor: color,
    borderWidth: 1,
    borderRadius: 7,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    padding: 15,
    marginTop: 15,
  }),
  imageRankList: {
    width: 50,
    height: 50,
    borderRadius: 7,
    marginLeft: 20,
    marginRight: 20,
  },
  starRankList: {
    position: "absolute",
    bottom: -11,
    right: 8,
  },
  nameRankList: {
    fontFamily: "Nunito-ExtraBold",
    fontSize: 14,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  pointsRankList: (textColor) => ({
    color: textColor,
    fontFamily: "Nunito-ExtraBold",
    fontSize: 12,
    letterSpacing: 1,
    textTransform: "uppercase",
    position: "absolute",
    right: 15,
  }),
});
